app:
  jwtSecret: teststs
  jwtExpirationInMs: 30
  name: booking-app-user
  upload:
    path: upload
springdoc:
  swagger-ui:
    path: /swagger/doc
    operationsSorter: method
  api-docs:
    path: /swagger/api-docs
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: user
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
server:
  port: 8081
  protocol-header: x-forwarded-proto
